services:
  postgres:
    container_name: appname-postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=appname-dev
    ports:
      - 6500:5432
    volumes:
      - ./.data/db:/var/lib/postgresql/data/

  redis:
    container_name: appname-redis
    image: redis
    ports:
      - 63790:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass redis

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/appname?schema=public
      - NODE_ENV=development
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - postgres

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - backend

